# Generated by Django 3.2.4 on 2021-07-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_domain_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='qr_code',
            field=models.TextField(),
        ),
    ]
